package icfp.endo;

public enum RNAToken {
  FAILED, DONE, ADD_BLACK, ADD_RED, ADD_GREEN, ADD_YELLOW, ADD_BLUE, ADD_MAGENTA, ADD_CYAN, ADD_WHITE, ADD_TRANS,
  ADD_OPAQUE, EMPTY_BUCKET, MOVE, TURN_CW, TURN_CCW, MARK, LINE, TRYFILL, ADD_BITMAP, COMPOSE, CLIP
}
